name: Rancher Prime Documentation - Build the Antora site and push to the gh-pages branch
on:
  push:
    branches: [test]
  pull_request:
  workflow_dispatch:
concurrency:
  group: deploy-gh-pages
  cancel-in-progress: false
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Antora with the Antora Lunr Extension
      run: make environment
    - name: Generate Site
      run: make local
    - name: Push the static site content to gh-pages branch
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        mv build/site ../site-temp
        git fetch origin gh-pages
        git checkout -b deploy-${GITHUB_REF} gh-pages
        rm -rf *
        mv ../site-temp/* .
        git add .
        git commit -m "Deploy ref: ${GITHUB_REF}, ref_name ${GITHUB_REF_NAME} to gh-pages branch"
        git push origin deploy-${GITHUB_REF}
        gh pr create --base gh-pages --head deploy-${GITHUB_REF} --title "Deploy ${GITHUB_REF} to gh-pages" --body "Deploy ref: ${GITHUB_REF}, ref_name ${GITHUB_REF_NAME} to gh-pages branch"
